name: WordPress Coding Standards

on: pull_request

jobs:
  wordpress-coding-standards:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Codesniff against the WordPress Core Coding Standards...
      run: |
        composer install
        ./vendor/bin/phpcs .
